### ISSUE TITLE
Problem with .current.wall

### ISSUE THREAD

**Issue by samjoshuadud** [Axenide/Ax-Shell#24]
Hi! I've been using your bar for the past few weeks and tried updating just now. 

There's somewhat an issue with the wallpaper specifically in .~/current.wall

```
Traceback (most recent call last):
  File "/home/punisher/.config/Ax-Shell/main.py", line 26, in <module>
    notch = Notch()
  File "/home/punisher/.config/Ax-Shell/modules/notch.py", line 35, in __init__
    self.dashboard = Dashboard(notch=self)
                     ~~~~~~~~~^^^^^^^^^^^^
  File "/home/punisher/.config/Ax-Shell/modules/dashboard.py", line 37, in __init__
    self.widgets = Widgets(notch=self.notch)
                   ~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/punisher/.config/Ax-Shell/modules/dashboard_modules/widgets.py", line 69, in __init__
    self.player = Player()
                  ~~~~~~^^
  File "/home/punisher/.config/Ax-Shell/modules/player.py", line 313, in __init__
    pb = PlayerBox(mpris_player=None)
  File "/home/punisher/.config/Ax-Shell/modules/player.py", line 41, in __init__
    self.cover = CircleImage(
                 ~~~~~~~~~~~^
        name="player-cover",
        ^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        v_align="center",
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/punisher/.config/Ax-Shell/widgets/circle_image.py", line 63, in __init__
    pix = GdkPixbuf.Pixbuf.new_from_file(image_file)
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “/home/punisher/.current.wall”: Too many levels of symbolic links (11)
```

I checked the symbolic link and apparently it's looping onto itself?

```
ls -l /home/punisher/.current.wall

lrwxrwxrwx 1 punisher users 28 Feb 23 22:30 /home/punisher/.current.wall -> /home/punisher/.current.wall

```

I tried manually recreating the symlink and it does work but whenever i terminated the python program and re-runs it, I am faced with the error again.

I saw that the others has the same issue with their .current.wall and tried doing the solution you've provided by deleting the .current.wall and the config.json of the Ax-Shell but still the same.

**Comment by Axenide** [comment]
Hi, yeah I fixed this, please use the latest commit.
I'm not using symlinks anymore, so this shouldn't happen. Delete the already existing symlink and you should be good to go. :)

**Comment by samjoshuadud** [comment]
Im at the latest commit and I'm still encountering the same problem

```
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “/home/punisher/.current.wall”: No such file or directory (4)
```

**Comment by Axenide** [comment]
Did you delete both the symlink and config.json?

**Comment by Axenide** [comment]
I see you are using my Starship prompt, did you perhaps install my dotfiles?

**Comment by samjoshuadud** [comment]
I did but haven't updated it since

**Comment by samjoshuadud** [comment]
No problem.  Ill try to tweak it myself. Thanks!

**Comment by Axenide** [comment]
Thank you, please tell me if you can fix it. :)

**Comment by samjoshuadud** [comment]
I did. I just pulled the latest changes of your dotfiles :)
